# Generated by Django 6.0.5 on 2026-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacherinvitecode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
