# Generated by Django 5.2.12 on 2026-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studentprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='crystals',
            field=models.IntegerField(default='0'),
        ),
    ]
